"""
src/scripts/ai_orchestrator.py
Zero-Dependency Pre-Market AI Intelligence Layer Orchestrator.
Designed to run at 08:35 AM IST between:
  - 10:30 PM IST: screener.py (generates Top 50 Math Baseline)
  - 08:55 AM IST: update_symbols.py (pushes tokens to symbols.json for WebSocket/Redis)
"""

import os
import sys
import json
import logging
import pandas as pd
from datetime import datetime
from zoneinfo import ZoneInfo
from dotenv import load_dotenv
from telegram_reporter import TelegramReporter

current_dir = os.path.dirname(os.path.abspath(__file__))
project_root = os.path.abspath(os.path.join(current_dir, "../../"))
if project_root not in sys.path:
    sys.path.insert(0, project_root)

env_path = os.path.join(project_root, ".env")
load_dotenv(dotenv_path=env_path)

from src.scripts.ai_catalyst_crawler import CatalystCrawler
from src.scripts.ai_evaluator import CatalystEvaluator, NEUTRAL_FALLBACK_RESULT
from src.scripts.hybrid_ranker import HybridRanker
from src.scripts.cohort_blender import CohortBlender

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)-7s | %(name)s | %(message)s"
)
logger = logging.getLogger("AIOrchestrator")
IST = ZoneInfo("Asia/Kolkata")


class PreMarketAIOrchestrator:
    def __init__(self, w_math: float = 0.70, w_ai: float = 0.30):
        self.w_math = float(os.getenv("HYBRID_W_MATH", w_math))
        self.w_ai = float(os.getenv("HYBRID_W_AI", w_ai))

        self.db_path = os.path.join(project_root, "master_history.db")
        self.target_ticks_path = os.path.join(project_root, "target_ticks.json")
        self.baseline_backup_path = os.path.join(project_root, "math_top50_baseline.json")
        self.ai_catalyst_ticks_path = os.path.join(project_root, "ai_catalyst_ticks.json")
        self.csv_rankings_path = os.path.join(project_root, "live_screener_rankings.csv")

        self.crawler = CatalystCrawler()
        self.evaluator = CatalystEvaluator()
        self.ranker = HybridRanker(
            db_path=self.db_path,
            csv_rankings_path=self.csv_rankings_path,
            w_math=self.w_math,
            w_ai=self.w_ai
        )

    def load_math_top_50(self) -> list:
        """
        Safely loads the Top-50 mathematical baseline generated by screener.py at 10:30 PM.
        Saves a snapshot to math_top50_baseline.json so re-running ai_orchestrator.py
        before 8:55 AM never loses the original 50 math candidates.
        """
        if os.path.exists(self.target_ticks_path):
            with open(self.target_ticks_path, "r") as f:
                data = json.load(f)

            if isinstance(data, list) and len(data) > 0 and "cohort" not in data[0]:
                with open(self.baseline_backup_path, "w") as bf:
                    json.dump(data, bf, indent=4)
                logger.info("Backed up fresh 10:30 PM math Top-50 to math_top50_baseline.json")
                return data

        if os.path.exists(self.baseline_backup_path):
            with open(self.baseline_backup_path, "r") as bf:
                data = json.load(bf)
            if isinstance(data, list) and len(data) > 0:
                logger.info("Loaded 10:30 PM math Top-50 from math_top50_baseline.json")
                return data

        if os.path.exists(self.csv_rankings_path) and os.path.getsize(self.csv_rankings_path) > 0:
            df = pd.read_csv(self.csv_rankings_path).head(50)
            reconstructed = [
                {
                    "symbol": str(row["symbol"]),
                    "token": str(row["token"]),
                    "master_score": float(row["master_score"])
                }
                for _, row in df.iterrows()
            ]
            logger.info("Reconstructed Top-50 math baseline from live_screener_rankings.csv")
            return reconstructed

        if os.path.exists(self.target_ticks_path):
            with open(self.target_ticks_path, "r") as f:
                return json.load(f)

        raise FileNotFoundError("Could not find 10:30 PM math baseline in target_ticks.json or CSV.")

    def execute_pipeline(self):
        start_time = datetime.now(IST)
        logger.info("==========================================================")
        logger.info(f" BOOTING PRE-MARKET AI CATALYST ENGINE ({start_time.strftime('%H:%M:%S IST')})")
        logger.info("==========================================================")

        try:
            # Step 0: Load Top 50 Math Baseline
            math_top_50 = self.load_math_top_50()
            top_50_symbols = [item["symbol"] for item in math_top_50]
            logger.info(f"[STEP 0] Loaded {len(math_top_50)} mathematical baseline candidates.")

            # Step 1: Crawl Overnight NSE Filings, Bulk/Block Deals, Board Meetings & Insider PIT
            logger.info("[STEP 1] Crawling overnight NSE filings, bulk deals, board meetings & insider PIT...")
            math_filings_map, broad_filings_map = self.crawler.fetch_all_filings(top_50_symbols)

            # Step 2: Evaluate Filings via LLM with Liquidity Context
            logger.info("[STEP 2] Evaluating Top-50 Math stocks & Broad Market catalysts via Gemini...")
            active_math_filings = {sym: flist for sym, flist in math_filings_map.items() if flist}
            math_ai_evals = self.evaluator.evaluate_batch(
                active_math_filings,
                stock_context_map=self.ranker.symbol_to_context
            )
            broad_ai_evals = self.evaluator.evaluate_batch(
                broad_filings_map,
                stock_context_map=self.ranker.symbol_to_context
            )

            full_math_evals = {
                sym: math_ai_evals.get(sym, dict(NEUTRAL_FALLBACK_RESULT))
                for sym in top_50_symbols
            }

            # Step 3: Math + AI Blending (Top 15)
            logger.info(f"[STEP 3] Computing Hybrid Re-Ranking (w_math={self.w_math}, w_ai={self.w_ai})...")
            hybrid_top_15 = self.ranker.rank_hybrid_top_15(math_top_50, full_math_evals)

            # Step 4: Pure AI Discovery Universe (Top 20 -> ai_catalyst_ticks.json)
            logger.info("[STEP 4] Filtering & ranking Pure AI Discovery Universe against master_history.db...")
            pure_ai_top_20 = self.ranker.rank_pure_ai_top_20(
                broad_ai_evals,
                output_json_path=self.ai_catalyst_ticks_path
            )

            # Step 5: Master Cohort Handoff (15 Hybrid + 10 Pure AI -> target_ticks.json)
            logger.info("[STEP 5] Blending cohorts and writing target_ticks.json...")
            final_contract = CohortBlender.blend_and_export(
                hybrid_top_15=hybrid_top_15,
                pure_ai_top_20=pure_ai_top_20,
                target_ticks_path=self.target_ticks_path,
                hybrid_quota=15,
                pure_ai_quota=10,
                min_total_targets=50
            )
            # Step 6: Dispatch Pre-Market Intelligence Briefing to Telegram
            logger.info("[STEP 6] Dispatching pre-market audit to Telegram...")
            reporter = TelegramReporter()
            reporter.dispatch()
            elapsed = (datetime.now(IST) - start_time).total_seconds()
            logger.info(f"[SUCCESS] AI Orchestrator finished in {elapsed:.2f}s. Total symbols handed off: {len(final_contract)}")
    
        except Exception as e:
            logger.error(f"[CRITICAL FAIL-SAFE] AI Orchestrator encountered error: {e}")
            logger.info("Applying fail-safe: Preserving Top 15 mathematical picks with neutral 0.50 AI score.")
            self._apply_emergency_fallback()

    def _apply_emergency_fallback(self):
        try:
            math_top_50 = self.load_math_top_50()
            fallback_list = []
            for item in math_top_50[:50]:
                m_score = float(item.get("master_score", 0.0))
                f_score = round((self.w_math * m_score) + (self.w_ai * 0.50), 4)
                fallback_list.append({
                    "symbol": item["symbol"],
                    "token": str(item["token"]),
                    "master_score": round(m_score, 4),
                    "ai_score": 0.50,
                    "final_score": f_score,
                    "cohort": "HYBRID_MATH_AI"
                })
            with open(self.target_ticks_path, "w") as f:
                json.dump(fallback_list, f, indent=4)
        except Exception as inner_e:
            logger.error(f"Emergency fallback could not rewrite target_ticks.json: {inner_e}")


if __name__ == "__main__":
    orchestrator = PreMarketAIOrchestrator()
    orchestrator.execute_pipeline()