"""Strategy engine with risk management for live trading."""

import asyncio
import logging
from abc import ABC, abstractmethod
from collections import defaultdict
from dataclasses import dataclass, field
from datetime import datetime, timezone
from decimal import Decimal
from enum import Enum
from typing import Any

from src.pipeline.websocket_client import DhanWebSocketIngester
from src.trading.execution_client import (
    DhanExecutionClient,
    OrderRequest,
    OrderResponse,
    OrderSide,
    OrderType,
    OrderValidity,
)

logger = logging.getLogger(__name__)


class SignalType(Enum):
    BUY = "BUY"
    SELL = "SELL"
    CLOSE = "CLOSE"
    HOLD = "HOLD"


@dataclass(frozen=True, slots=True)
class Signal:
    """Trading signal generated by a strategy."""
    security_id: int
    signal_type: SignalType
    quantity: int
    price: Decimal | None = None
    trigger_price: Decimal | None = None
    order_type: OrderType = OrderType.MARKET
    validity: OrderValidity = OrderValidity.DAY
    metadata: dict[str, Any] = field(default_factory=dict)
    timestamp: datetime = field(default_factory=lambda: datetime.now(timezone.utc))


@dataclass(frozen=True, slots=True)
class Position:
    """Current position state."""
    security_id: int
    quantity: int
    avg_price: Decimal
    unrealized_pnl: Decimal = Decimal("0")
    realized_pnl: Decimal = Decimal("0")
    last_update: datetime = field(default_factory=lambda: datetime.now(timezone.utc))


@dataclass(slots=True)
class RiskLimits:
    """Risk management configuration."""
    max_open_positions: int = 10
    max_position_size: int = 1000
    max_order_size: int = 500
    max_daily_loss: Decimal = Decimal("50000")
    max_drawdown_pct: float = 0.05
    hard_stop_loss_pct: float = 0.02
    max_open_orders: int = 20


@dataclass(slots=True)
class RiskState:
    """Current risk state tracking."""
    open_positions: dict[int, Position] = field(default_factory=dict)
    open_orders: dict[str, OrderResponse] = field(default_factory=dict)
    daily_pnl: Decimal = Decimal("0")
    peak_equity: Decimal = Decimal("0")
    current_equity: Decimal = Decimal("0")
    blocked: bool = False
    block_reason: str = ""


class BaseStrategy(ABC):
    """Abstract base class for trading strategies."""

    def __init__(self, name: str, security_ids: list[int]) -> None:
        self.name = name
        self.security_ids = security_ids
        self._running = False

    @abstractmethod
    async def on_tick(self, tick: dict[str, Any]) -> list[Signal]:
        """Process incoming tick and generate signals.

        Args:
            tick: Raw tick data from WebSocket.

        Returns:
            List of Signal objects (empty if no action).
        """
        pass

    @abstractmethod
    async def on_start(self) -> None:
        """Called when strategy starts."""
        pass

    @abstractmethod
    async def on_stop(self) -> None:
        """Called when strategy stops."""
        pass

    async def start(self) -> None:
        self._running = True
        await self.on_start()

    async def stop(self) -> None:
        self._running = False
        await self.on_stop()


class RiskManager:
    """Pre-trade risk validation layer."""

    def __init__(self, limits: RiskLimits) -> None:
        self._limits = limits
        self._state = RiskState()
        self._lock = asyncio.Lock()

    async def validate_order(
        self,
        signal: Signal,
        current_price: Decimal | None = None,
    ) -> tuple[bool, str]:
        """Validate order against risk limits.

        Args:
            signal: Proposed trading signal.
            current_price: Current market price for PnL calc.

        Returns:
            Tuple of (allowed: bool, reason: str).
        """
        async with self._lock:
            if self._state.blocked:
                return False, f"Trading blocked: {self._state.block_reason}"

            # Max open positions
            if len(self._state.open_positions) >= self._limits.max_open_positions:
                if signal.security_id not in self._state.open_positions:
                    return False, f"Max open positions ({self._limits.max_open_positions}) reached"

            # Max position size
            pos = self._state.open_positions.get(signal.security_id)
            current_qty = pos.quantity if pos else 0

            if signal.signal_type == SignalType.BUY:
                new_qty = current_qty + signal.quantity
            elif signal.signal_type == SignalType.SELL:
                new_qty = current_qty - signal.quantity
            else:
                new_qty = abs(current_qty)

            if abs(new_qty) > self._limits.max_position_size:
                return False, f"Position size {abs(new_qty)} exceeds limit {self._limits.max_position_size}"

            # Max order size
            if signal.quantity > self._limits.max_order_size:
                return False, f"Order size {signal.quantity} exceeds limit {self._limits.max_order_size}"

            # Max open orders
            if len(self._state.open_orders) >= self._limits.max_open_orders:
                return False, f"Max open orders ({self._limits.max_open_orders}) reached"

            # Daily loss limit
            if self._state.daily_pnl <= -self._limits.max_daily_loss:
                self._state.blocked = True
                self._state.block_reason = f"Daily loss limit hit: {self._state.daily_pnl}"
                return False, self._state.block_reason

            # Drawdown limit
            if self._state.peak_equity > 0:
                drawdown = (self._state.peak_equity - self._state.current_equity) / self._state.peak_equity
                if drawdown >= self._limits.max_drawdown_pct:
                    self._state.blocked = True
                    self._state.block_reason = f"Max drawdown {drawdown:.2%} exceeded"
                    return False, self._state.block_reason

            return True, "OK"

    async def apply_stop_loss(self, signal: Signal, entry_price: Decimal) -> Signal:
        """Apply hard stop loss to signal if needed."""
        if signal.signal_type in (SignalType.BUY, SignalType.SELL):
            stop_pct = self._limits.hard_stop_loss_pct
            if signal.signal_type == SignalType.BUY:
                trigger = entry_price * (1 - Decimal(str(stop_pct)))
            else:
                trigger = entry_price * (1 + Decimal(str(stop_pct)))

            if signal.order_type == OrderType.MARKET:
                return Signal(
                    security_id=signal.security_id,
                    signal_type=signal.signal_type,
                    quantity=signal.quantity,
                    price=signal.price,
                    trigger_price=trigger,
                    order_type=OrderType.STOP_LOSS_MARKET,
                    validity=signal.validity,
                    metadata={**signal.metadata, "stop_loss": "auto"},
                    timestamp=signal.timestamp,
                )
        return signal

    async def update_position(self, order: OrderResponse, fill_price: Decimal, fill_qty: int) -> None:
        """Update position state after fill."""
        async with self._lock:
            if order.order_id in self._state.open_orders:
                del self._state.open_orders[order.order_id]

    async def update_equity(self, equity: Decimal) -> None:
        """Update equity for drawdown tracking."""
        async with self._lock:
            self._state.current_equity = equity
            if equity > self._state.peak_equity:
                self._state.peak_equity = equity

    async def update_daily_pnl(self, pnl: Decimal) -> None:
        """Update daily PnL."""
        async with self._lock:
            self._state.daily_pnl += pnl

    def get_state(self) -> RiskState:
        """Get current risk state snapshot."""
        return self._state


class StrategyEngine:
    """Orchestrates strategies, risk management, and order execution."""

    def __init__(
        self,
        execution_client: DhanExecutionClient,
        risk_limits: RiskLimits | None = None,
        tick_buffer_size: int = 1000,
    ) -> None:
        self._execution = execution_client
        self._risk = RiskManager(risk_limits or RiskLimits())
        self._strategies: dict[str, BaseStrategy] = {}
        self._ingester: DhanWebSocketIngester | None = None
        self._tick_queue: asyncio.Queue[dict[str, Any]] = asyncio.Queue(maxsize=tick_buffer_size)
        self._running = False
        self._processor_task: asyncio.Task | None = None
        self._order_tracker: dict[str, asyncio.Task] = {}

    def register_strategy(self, strategy: BaseStrategy) -> None:
        """Register a strategy with the engine."""
        if strategy.name in self._strategies:
            raise ValueError(f"Strategy '{strategy.name}' already registered")
        self._strategies[strategy.name] = strategy
        logger.info("Strategy registered", extra={"strategy_name": strategy.name, "securities": strategy.security_ids})

    def set_ingester(self, ingester: DhanWebSocketIngester) -> None:
        """Link WebSocket ingester for tick consumption."""
        self._ingester = ingester

    async def _process_ticks(self) -> None:
        """Main tick processing loop."""
        while self._running:
            try:
                tick = await asyncio.wait_for(self._tick_queue.get(), timeout=1.0)
                await self._dispatch_tick(tick)
            except asyncio.TimeoutError:
                continue
            except Exception as exc:
                logger.error("Tick processing error", extra={"error": str(exc), "error_type": type(exc).__name__})

    async def _dispatch_tick(self, tick: dict[str, Any]) -> None:
        """Dispatch tick to relevant strategies."""
        security_id = tick.get("security_id")
        if security_id is None:
            return

        for strategy in self._strategies.values():
            if security_id in strategy.security_ids:
                try:
                    signals = await strategy.on_tick(tick)
                    for signal in signals:
                        await self._handle_signal(signal)
                except Exception as exc:
                    logger.error(
                        "Strategy error",
                        extra={"strategy": strategy.name, "security_id": security_id, "error": str(exc)},
                    )

    async def _handle_signal(self, signal: Signal) -> None:
        """Process signal through risk and execute."""
        # Get current price for risk checks
        current_price = signal.price or Decimal(str(signal.trigger_price or 0))

        # Validate against risk limits
        allowed, reason = await self._risk.validate_order(signal, current_price)
        if not allowed:
            logger.warning("Signal rejected by risk", extra={"signal": signal.__dict__, "reason": reason})
            return

        # Apply hard stop loss
        if signal.order_type == OrderType.MARKET and current_price > 0:
            signal = await self._risk.apply_stop_loss(signal, current_price)

        # Convert to order request
        order_req = OrderRequest(
            security_id=signal.security_id,
            exchange_segment="NSE_EQ",
            transaction_type=OrderSide.BUY if signal.signal_type == SignalType.BUY else OrderSide.SELL,
            order_type=signal.order_type,
            quantity=signal.quantity,
            price=float(signal.price) if signal.price else None,
            trigger_price=float(signal.trigger_price) if signal.trigger_price else None,
            validity=signal.validity,
        )

        # Execute order
        try:
            logger.info("Sending order", extra={"signal": signal.__dict__})
            response = await self._execution.place_order(order_req)

            # Track open order
            async with self._risk._lock:
                self._risk._state.open_orders[response.order_id] = response

            # Track order lifecycle
            task = asyncio.create_task(self._track_order(response.order_id, signal))
            self._order_tracker[response.order_id] = task

        except Exception as exc:
            logger.error("Order execution failed", extra={"signal": signal.__dict__, "error": str(exc)})

    async def _track_order(self, order_id: str, signal: Signal) -> None:
        """Monitor order until completion."""
        try:
            while True:
                await asyncio.sleep(2)
                status = await self._execution.get_order_status(order_id)

                if status.order_status in ("COMPLETE", "CANCELLED", "REJECTED"):
                    async with self._risk._lock:
                        self._risk._state.open_orders.pop(order_id, None)

                    if status.order_status == "COMPLETE":
                        logger.info("Order filled", extra={"order_id": order_id, "signal": signal.__dict__})
                    elif status.order_status == "REJECTED":
                        logger.warning("Order rejected", extra={"order_id": order_id, "error": status.error_message})
                    break

        except asyncio.CancelledError:
            pass
        except Exception as exc:
            logger.error("Order tracking error", extra={"order_id": order_id, "error": str(exc)})
        finally:
            self._order_tracker.pop(order_id, None)

    async def start(self) -> None:
        """Start the strategy engine."""
        if self._running:
            return

        self._running = True

        # Start all strategies
        for strategy in self._strategies.values():
            await strategy.start()

        # Start tick processor
        self._processor_task = asyncio.create_task(self._process_ticks())

        logger.info("Strategy engine started", extra={"strategies": list(self._strategies.keys())})

    async def stop(self) -> None:
        """Stop the strategy engine gracefully."""
        self._running = False

        # Stop tick processor
        if self._processor_task:
            self._processor_task.cancel()
            try:
                await self._processor_task
            except asyncio.CancelledError:
                pass

        # Cancel order trackers
        for task in self._order_tracker.values():
            task.cancel()
        await asyncio.gather(*self._order_tracker.values(), return_exceptions=True)

        # Stop strategies
        for strategy in self._strategies.values():
            await strategy.stop()

        logger.info("Strategy engine stopped")

    async def enqueue_tick(self, tick: dict[str, Any]) -> bool:
        """Add tick to processing queue (called from WebSocket ingester).

        Returns:
            True if enqueued, False if queue full.
        """
        try:
            self._tick_queue.put_nowait(tick)
            return True
        except asyncio.QueueFull:
            logger.warning("Tick queue full, dropping tick", extra={"security_id": tick.get("security_id")})
            return False
